# Generated by Django 3.1 on 2020-08-24 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link',
            new_name='links',
        ),
    ]
